local_repository(
    name = "openapi_tools_generator_bazel",
    path = "../..",
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

######################
# Golang
######################
# https://github.com/bazelbuild/rules_go/releases
http_archive(
    name = "io_bazel_rules_go",
    sha256 = "6dc2da7ab4cf5d7bfc7c949776b1b7c733f05e56edc4bcd9022bb249d2e2a996",
    urls = ["https://github.com/bazelbuild/rules_go/releases/download/v0.39.1/rules_go-v0.39.0.zip"],
)

load("@io_bazel_rules_go//go:deps.bzl", "go_register_toolchains", "go_rules_dependencies")

go_rules_dependencies()

go_register_toolchains(version = "1.20.3")

# Gazelle: https://github.com/bazelbuild/bazel-gazelle/releases
http_archive(
    name = "bazel_gazelle",
    sha256 = "727f3e4edd96ea20c29e8c2ca9e8d2af724d8c7778e7923a854b2c80952bc405",
    urls = ["https://github.com/bazelbuild/bazel-gazelle/releases/download/v0.30.0/bazel-gazelle-v0.30.0.tar.gz"],
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")
load("//:workspace.bzl", "go_dependencies")

# gazelle:repository_macro workspace.bzl%go_dependencies
go_dependencies()

gazelle_dependencies()

######################
# Aspect's Bazel
######################
# https://github.com/aspect-build/bazel-lib/releases
http_archive(
    name = "aspect_bazel_lib",
    sha256 = "5f3443b1d98a462a8b7330f4742483afc8b2d17c8555dd97ce4146f43e961718",
    strip_prefix = "bazel-lib-1.31.1",
    url = "https://github.com/aspect-build/bazel-lib/releases/download/v1.31.1/bazel-lib-v1.31.1.tar.gz",
)

load("@aspect_bazel_lib//lib:repositories.bzl", "aspect_bazel_lib_dependencies")

aspect_bazel_lib_dependencies()

#######################
# OpenAPI Generator
#######################
load("@openapi_tools_generator_bazel//:defs.bzl", "openapi_tools_generator_bazel_repositories")

openapi_tools_generator_bazel_repositories()
